---
apiVersion: v1
kind: Namespace
metadata:
  name: netshoot
  labels:
    name: netshoot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    com.illumio.app: attacker
    com.illumio.role: evil
  name: netshoot
  namespace: netshoot
  labels:
    app: netshoot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netshoot
  template:
    metadata:
      labels:
        app: netshoot
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot:latest
        command: ["/bin/bash", "-c"]
        args:
          - while true; do curl http://yelb-ui.yelb.svc.cluster.local; telnet yelb-db.yelb.svc.cluster.local 5432; telnet yelb-appserver.yelb.svc.cluster.local 4567; telnet redis-server.yelb.svc.cluster.local 6379; sleep 30; done;
            sleep infinity;
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
      restartPolicy: Always
